# Generated by Django 4.2.5 on 2023-10-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='see_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listles',
            name='last_viev',
            field=models.DateField(default='2001-09-11'),
        ),
        migrations.AddField(
            model_name='listles',
            name='time_viev',
            field=models.IntegerField(default=0),
        ),
    ]
