# Generated by Django 4.2.5 on 2023-10-02 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testback', '0002_lesson_see_time_listles_last_viev_listles_time_viev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listles',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listles', to='testback.lesson'),
        ),
        migrations.AlterField(
            model_name='listles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listuser', to='testback.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(related_name='prodless', to='testback.lesson'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lessons',
            field=models.ManyToManyField(related_name='userless', through='testback.ListLes', to='testback.lesson'),
        ),
    ]
