# Generated by Django 4.2.5 on 2023-10-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testback', '0004_alter_listles_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='products',
            field=models.ManyToManyField(related_name='prodless', to='testback.product'),
        ),
    ]
